### ISSUE TITLE
Unable to install Northstar

### ISSUE THREAD

**Issue by Ryuk47** [BigSpice/VTOL#52]
**Describe the bug**
Neither the Auto install, not manually setting the target destination results in the successfull installation of the Northstar client. Curiously, the VTOL installer shows both its own as well as the Northstar version number as 0.0.0.

I tried the installer (default install location) as well as the portable version with the same results.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11

**Additional context**

**Comment by BigSpice** [comment]
please try running as admin

**Comment by Ryuk47** [comment]
Reinstalled it again just now, running the exe with admin privileges for the first time results in the vorrect VTOL version being displayed. However, neither the auto install nor the location of the titanfall 2 folder seems to work still.
I'm receiving the "Northstar client will now install" message, immediately followed by "Northstar not found, auto install failed".

**Comment by BigSpice** [comment]
should  be fixed in release https://github.com/BigSpice/VTOL/releases/tag/v2.0.3

**Comment by Ryuk47** [comment]
Unfortunately the issue persists still. Could the described descrepancy witht the slightly newer .net runtime version be at fault here? Alternatively, is the lack of properly displayed version numbers any pointert here?
My PC runs a relatively fresh install of Windows 11 Pro, my user being the sole Admin account, with me not having configured any extraordinary security settings or the such.

**Comment by BigSpice** [comment]
Win 11 is not officially supported because of odd issues like these.
Try installing the Northstar install from thunderstore.

**Comment by BigSpice** [comment]
@Ryuk47

**Comment by BigSpice** [comment]
Closed Due to 3 Days of Incativity.

**Comment by BigSpice** [comment]
Issue Solved in 2.0.4
